Fix a linker dependecy problem that showed up when building on CentOS 7. I'm not sure why this didn't show up on the ofstest machines (Scientific Linux 6), but on the pvfs machines I was getting the following error when trying to build:
/usr/bin/ld: lib/libpvfs2-server.a(rdma-server.o): undefined reference to symbol 'ibv_ack_async_event@@IBVERBS_1.1'
/usr/lib64/libibverbs.so.1: error adding symbols: DSO missing from command line


SVN revision 13046